export const MEXICAN_CITIES = [
  'Ciudad de México',
  'Guadalajara',
  'Monterrey',
  'Puebla',
  'Tijuana',
  'León',
  'Juárez',
  'Zapopan',
  'Mérida',
  'San Luis Potosí',
  'Querétaro',
  'Torreón',
  'Chihuahua',
  'Aguascalientes',
  'Mexicali',
  'Saltillo',
  'Cancún',
  'Hermosillo',
  'Morelia',
  'Culiacán',
  'Veracruz',
  'Acapulco',
  'Toluca',
  'Oaxaca',
  'Pachuca',
] as const;

export type MexicanCity = typeof MEXICAN_CITIES[number]; 