export const giros = [
  "Desarrollo de Software",
  "Diseño y UX/UI",
  "Marketing Digital",
  "Ventas",
  "Atención al Cliente",
  "Recursos Humanos",
  "Administración",
  "Finanzas y Contabilidad",
  "Legal",
  "Operaciones",
  "Logística",
  "Producción",
  "Calidad",
  "Investigación y Desarrollo",
  "Educación y Formación",
  "Salud",
  "Tecnología de la Información",
  "Seguridad",
  "Comunicaciones",
  "Consultoría",
  "Compras",
  "Mantenimiento",
  "Servicio Técnico",
  "Comercio Exterior",
  "Bienes Raíces",
  "Construcción",
  "Agricultura",
  "Minería",
  "Energía",
  "Transporte",
  "Otros"
] as const;

export type Giro = typeof giros[number]; 